table streaming_data
	lineageTag: 56401bfe-d3e7-47db-9335-0c39536813ef

	column venta_id
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 7b3c17e7-fe12-4cdd-8062-dc4fee0c19af
		summarizeBy: none
		sourceColumn: venta_id

		annotation SummarizationSetBy = Automatic

	column fecha_venta
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 84fcbeed-ac32-42b7-b034-0003e78fb274
		summarizeBy: none
		sourceColumn: fecha_venta

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 905560f5-e8dd-4d71-ad70-058e10bdb3ed
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column ciudad
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 7bdd0699-8936-40f0-bf68-3c9488c32186
		summarizeBy: none
		sourceColumn: ciudad

		annotation SummarizationSetBy = Automatic

	column tienda
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 4f9f4d85-63b7-4625-b0f8-a4e56be1134e
		summarizeBy: none
		sourceColumn: tienda

		annotation SummarizationSetBy = Automatic

	column categoria
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 9ae67b18-3982-441c-afd5-9198218b80e2
		summarizeBy: none
		sourceColumn: categoria

		annotation SummarizationSetBy = Automatic

	column marca
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 2cd803a5-0812-4cf0-9e9f-37bbb4f8feee
		summarizeBy: none
		sourceColumn: marca

		annotation SummarizationSetBy = Automatic

	column producto
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 5068c521-cf3d-4ccb-aa52-1259e0283911
		summarizeBy: none
		sourceColumn: producto

		annotation SummarizationSetBy = Automatic

	column precio_unitario
		dataType: double
		sourceProviderType: double
		lineageTag: 8fcb38fb-62d1-4bb9-9bcf-f52820eea312
		summarizeBy: sum
		sourceColumn: precio_unitario

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column precio_ultima_compra
		dataType: double
		sourceProviderType: double
		lineageTag: 2d28ce38-d92c-472d-8a76-49a53761266b
		summarizeBy: sum
		sourceColumn: precio_ultima_compra

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cantidad
		dataType: double
		sourceProviderType: double
		lineageTag: 8970f951-31d6-4fee-b192-8a18a572ad12
		summarizeBy: sum
		sourceColumn: cantidad

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column descuento_pct
		dataType: int64
		sourceProviderType: bigint
		lineageTag: 4fd4fed8-1df1-4144-a193-ccde51167f0f
		summarizeBy: sum
		sourceColumn: descuento_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column descuento_monto
		dataType: int64
		sourceProviderType: bigint
		lineageTag: 0266f843-23a2-4e48-bd0d-88bec13bd01b
		summarizeBy: sum
		sourceColumn: descuento_monto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column subtotal
		dataType: double
		sourceProviderType: double
		lineageTag: d2af6faf-5426-4309-b25b-cce798d94648
		summarizeBy: sum
		sourceColumn: subtotal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column impuesto_pct
		dataType: int64
		sourceProviderType: bigint
		lineageTag: 221b356a-f5f3-4a7b-ae31-059f1264e808
		summarizeBy: sum
		sourceColumn: impuesto_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column impuesto_monto
		dataType: double
		sourceProviderType: double
		lineageTag: d5e33f83-b3c9-4f4a-bc19-9f2e3200b11d
		summarizeBy: sum
		sourceColumn: impuesto_monto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_linea
		dataType: double
		sourceProviderType: double
		lineageTag: 8d7f1e9c-7b53-4f41-89fe-c6cc28ff9bf7
		summarizeBy: sum
		sourceColumn: total_linea

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column canal_venta
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: a7da6c06-6a55-4fbc-901c-9f1168ababc4
		summarizeBy: none
		sourceColumn: canal_venta

		annotation SummarizationSetBy = Automatic

	column terminal_origen
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 0fcb6592-d1ac-4676-bda0-fd7f3956d9e3
		summarizeBy: none
		sourceColumn: terminal_origen

		annotation SummarizationSetBy = Automatic

	column EventProcessedUtcTime
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetimeoffset
		lineageTag: 7d40c7ed-7be9-4bd2-9e9d-25b11739b7ef
		summarizeBy: none
		sourceColumn: EventProcessedUtcTime

		annotation SummarizationSetBy = Automatic

	column PartitionId
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 45a9aef2-b779-4444-83de-8648d35b3f06
		summarizeBy: count
		sourceColumn: PartitionId

		annotation SummarizationSetBy = Automatic

	column EventEnqueuedUtcTime
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetimeoffset
		lineageTag: 0a6cd072-a345-42c5-aa84-f9da48fb6751
		summarizeBy: none
		sourceColumn: EventEnqueuedUtcTime

		annotation SummarizationSetBy = Automatic

	partition streaming_data = m
		mode: directQuery
		source =
				let
				    Origen = AzureDataExplorer.Contents(
				    "https://trd-1b0181phbm05pez86t.z5.kusto.fabric.microsoft.com",
				    "KQL_EventHouse", "streaming_data"
				),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"fecha_venta", type datetime}, {"total_linea", type number}, {"precio_unitario", type number}, {"precio_ultima_compra", type number}, {"subtotal", type number}, {"impuesto_monto", type number}, {"cantidad", type number}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

